# Generated by Django 5.0.2 on 2024-04-10 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music_recommender', '0001_initial'),
        ('users', '0002_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_genre', models.CharField(blank=True, max_length=100, null=True)),
                ('favorite_artist', models.CharField(blank=True, max_length=100, null=True)),
                ('saved_tracks', models.ManyToManyField(blank=True, related_name='saved_by_users', to='music_recommender.musictrack')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
