# Generated by Django 5.0.2 on 2024-04-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_artist',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_genre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
