# Generated by Django 5.0.2 on 2024-04-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_favorite_artist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_genre',
        ),
    ]
