# Generated by Django 5.0.2 on 2024-04-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userprofile_favorite_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_genre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
