# Generated by Django 5.0.2 on 2024-04-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_recommender', '0002_remove_musictrack_tempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musictrack',
            name='artist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
