# Generated by Django 5.0.2 on 2024-04-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_recommender', '0004_remove_musictrack_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='musictrack',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
